#!/usr/bin/env bun
/**
 * promote-release-notes.ts — turn pending release notes into a versioned file.
 *
 * PRs accumulate user-visible bullets in
 * `apps/electron/resources/release-notes/next.md`. The in-app What's New
 * overlay only reads strict `X.Y.Z.md` files (see
 * packages/shared/src/release-notes/index.ts), so the pending file has to be
 * promoted to a versioned one before it can ship.
 *
 * This script performs that promotion for both channels:
 *
 *   - `build` job (nightly + stable): runs without `--reset`, so the versioned
 *     file exists only in the CI checkout and gets bundled into the artifact.
 *     Nothing is committed, so a cycle that eventually ships as a minor bump
 *     never leaves a speculative `X.Y.Z.md` behind on main.
 *   - `finalize` job (stable only): runs with `--reset` on a fresh checkout of
 *     main, so the promotion and the emptied `next.md` land in the same
 *     `chore(release): prepare v<version>` commit.
 *
 * The target filename is the stable core of the release version, so
 * `0.10.11-nightly.20260622.40` and `0.10.11` both promote to `0.10.11.md` —
 * nightly users and stable users see the same version string, and the overlay
 * (which compares against `whats-new-last-seen-version`) does not re-prompt.
 *
 * CLI:
 *   bun run scripts/release/promote-release-notes.ts --version <version> \
 *     [--root <dir>] [--reset] [--check] [--github-output]
 *
 * `--check` writes nothing: it fails when a stable release would ship with no
 * notes at all (no pending bullets and no already-promoted versioned file),
 * which is what the `release_meta` gate enforces before any build work.
 */

import { readFileSync, writeFileSync, appendFileSync, existsSync } from 'node:fs'
import { resolve, dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { resolveStableCore } from './resolve-nightly-release.ts'

/** Directory holding both the pending file and the versioned files. */
export const RELEASE_NOTES_DIR = 'apps/electron/resources/release-notes'

/** The accumulator PRs append to. */
export const PENDING_NOTES_FILENAME = 'next.md'

/** Canonical empty state of `next.md`, restored by `--reset`. */
export const PENDING_NOTES_TEMPLATE = `# Pending Release Notes

This file accumulates release notes for the next unreleased version. PRs that add user-visible behavior should append a bullet to the relevant section here. Versioned files (\`X.Y.Z.md\`) are generated by the release workflow — never create them in feature commits.

## Features

## Improvements

## Bug Fixes

## Breaking Changes
`

export interface NotesSection {
  readonly title: string
  readonly lines: readonly string[]
}

/**
 * Split a notes document into its `## ` sections, discarding everything before
 * the first one (the `# ` title and any instructional prose in `next.md`).
 */
export function parseNotesSections(text: string): NotesSection[] {
  const sections: NotesSection[] = []
  let current: { title: string; lines: string[] } | undefined

  for (const line of text.split('\n')) {
    const heading = /^##\s+(.*\S)\s*$/.exec(line)
    if (heading) {
      current = { title: heading[1], lines: [] }
      sections.push(current)
    } else if (current) {
      current.lines.push(line)
    }
  }

  return sections.map(({ title, lines }) => ({ title, lines: trimBlankEdges(lines) }))
}

function trimBlankEdges(lines: readonly string[]): string[] {
  let start = 0
  let end = lines.length
  while (start < end && lines[start].trim() === '') start += 1
  while (end > start && lines[end - 1].trim() === '') end -= 1
  return lines.slice(start, end)
}

/** True when any section carries at least one bullet. */
export function hasPendingEntries(text: string): boolean {
  return parseNotesSections(text).some((section) =>
    section.lines.some((line) => /^\s*[-*]\s+\S/.test(line)),
  )
}

/**
 * Merge pending sections into any already-promoted sections, preserving section
 * order (existing first, then sections only present in the pending file) and
 * dropping bullets that are byte-identical to one already carried over. A
 * stable release that was promoted by hand and then took further merges must
 * not lose either set of bullets.
 */
export function mergeNotesSections(
  existing: readonly NotesSection[],
  pending: readonly NotesSection[],
): NotesSection[] {
  const merged: NotesSection[] = existing.map((section) => ({ ...section }))

  for (const section of pending) {
    const target = merged.find((candidate) => candidate.title === section.title)
    if (!target) {
      merged.push({ ...section })
      continue
    }
    const seen = new Set(target.lines.map((line) => line.trim()).filter(Boolean))
    const additions = section.lines.filter((line) => {
      const key = line.trim()
      if (!key) return true
      if (seen.has(key)) return false
      seen.add(key)
      return true
    })
    const combined = trimBlankEdges([...target.lines, '', ...additions])
    merged[merged.indexOf(target)] = { title: target.title, lines: combined }
  }

  return merged
}

function renderNotes(title: string, sections: readonly NotesSection[]): string {
  const blocks = sections.map((section) =>
    section.lines.length > 0 ? `## ${section.title}\n\n${section.lines.join('\n')}` : `## ${section.title}`,
  )
  return `${title}\n\n${blocks.join('\n\n')}\n`
}

/** Extract the leading `# ` title, if the document has one. */
function readTitle(text: string): string | undefined {
  for (const line of text.split('\n')) {
    if (line.startsWith('# ')) return line.trimEnd()
    if (line.trim() !== '') break
  }
  return undefined
}

export interface PromotionResult {
  readonly version: string
  readonly filename: string
  readonly content: string
}

/**
 * Build the versioned document for `version` from the pending notes, merged
 * over `existingNotes` when that version was already promoted. Returns
 * undefined when there is nothing to promote.
 */
export function promoteReleaseNotes(
  pendingNotes: string,
  version: string,
  existingNotes?: string,
): PromotionResult | undefined {
  const core = resolveStableCore(version)
  if (!/^\d+\.\d+\.\d+$/.test(core)) {
    throw new Error(`Invalid release version '${version}': no X.Y.Z core.`)
  }
  if (!hasPendingEntries(pendingNotes)) {
    return undefined
  }

  const existingSections = existingNotes ? parseNotesSections(existingNotes) : []
  const sections = mergeNotesSections(existingSections, parseNotesSections(pendingNotes))
  // The overlay auto-injects `# v<version>` when a file has no title, so a bare
  // version header is all that is needed; a hand-written summary survives.
  const title = (existingNotes ? readTitle(existingNotes) : undefined) ?? `# v${core}`

  return { version: core, filename: `${core}.md`, content: renderNotes(title, sections) }
}

function repoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..')
}

interface CliArgs {
  version?: string
  root?: string
  reset: boolean
  check: boolean
  githubOutput: boolean
}

function parseArgs(argv: string[]): CliArgs {
  const args: CliArgs = { reset: false, check: false, githubOutput: false }
  for (let i = 0; i < argv.length; i += 1) {
    const flag = argv[i]
    const value = argv[i + 1]
    switch (flag) {
      case '--version':
        args.version = value
        i += 1
        break
      case '--root':
        args.root = value
        i += 1
        break
      case '--reset':
        args.reset = true
        break
      case '--check':
        args.check = true
        break
      case '--github-output':
        args.githubOutput = true
        break
      default:
        throw new Error(`Unknown argument: ${flag}`)
    }
  }
  return args
}

function main(): void {
  const args = parseArgs(process.argv.slice(2))
  if (!args.version) {
    throw new Error('Missing --version argument')
  }

  const notesDir = join(args.root ? resolve(args.root) : repoRoot(), RELEASE_NOTES_DIR)
  const pendingPath = join(notesDir, PENDING_NOTES_FILENAME)
  if (!existsSync(pendingPath)) {
    throw new Error(`Pending release notes not found: ${pendingPath}`)
  }

  const pending = readFileSync(pendingPath, 'utf-8')
  const core = resolveStableCore(args.version)
  const targetPath = join(notesDir, `${core}.md`)
  const existing = existsSync(targetPath) ? readFileSync(targetPath, 'utf-8') : undefined

  if (args.check) {
    if (!existing && !hasPendingEntries(pending)) {
      console.error(
        `::error::Stable release ${core} has no release notes: ${RELEASE_NOTES_DIR}/${PENDING_NOTES_FILENAME} has no entries and ${RELEASE_NOTES_DIR}/${core}.md does not exist. Append the user-visible changes to ${PENDING_NOTES_FILENAME} before releasing (see docs/operations/release.md).`,
      )
      process.exit(1)
    }
    console.log(`Release notes present for ${core}.`)
    return
  }

  const result = promoteReleaseNotes(pending, args.version, existing)

  if (!result) {
    console.log(
      `No pending release notes to promote for ${core}; leaving ${RELEASE_NOTES_DIR} unchanged.`,
    )
  } else {
    writeFileSync(targetPath, result.content)
    console.log(`Promoted ${PENDING_NOTES_FILENAME} → ${RELEASE_NOTES_DIR}/${result.filename}`)
    if (args.reset) {
      writeFileSync(pendingPath, PENDING_NOTES_TEMPLATE)
      console.log(`Reset ${RELEASE_NOTES_DIR}/${PENDING_NOTES_FILENAME}`)
    }
  }

  if (args.githubOutput) {
    const githubOutput = process.env.GITHUB_OUTPUT
    if (!githubOutput) {
      throw new Error('GITHUB_OUTPUT is not set')
    }
    appendFileSync(githubOutput, `promoted=${result ? 'true' : 'false'}\nnotes_version=${core}\n`)
  }
}

if (import.meta.main) {
  main()
}
